export const actions = {
  getAllCompaniesRequest: "getAllCompanies",
  getAllCompaniesSuccess: "getAllCompaniesSuccess",
  getAllCompaniesFail: "getAllCompaniesFail",
  getSingleCompanyRequest: "getSingleCompanyRequest",
  getSingleCompanySuccess: "getSingleCompanySuccess",
  getSingleCompanyFail: "getSingleCompanyFail",
  editCompanyRequest: "editCompanyRequest",
  editCompanySuccess: "editCompanySuccess",
  editCompanyFail: "editCompanyFail",
  companiesFilter: "companiesFilter",
  companyTags: "companyTags",
  createRatingCompanyRequest: "createRatingCompanyRequest",
  createRatingCompanySuccess: "createRatingCompanySuccess",
  createRatingCompanyFail: "createRatingCompanyFail",
  editCompanyImageGalety: "editCompanyImageGalety",
  editCompanyMainImage: "editCompanyMainImage",
  editCompanyImageSuccess: "editCompanyImageSuccess",
  getUserCompanyRatingRequest: "getUserCompanyRatingRequest",
  getUserCompanyRatingSuccess: "getUserCompanyRatingSuccess",
  getUserCompanyRatingFail: "getUserCompanyRatingFail",
};