export const actions = {
  getAllCompaniesRequest: "getAllCompanies",
  getAllCompaniesSuccess: "getAllCompaniesSuccess",
  getAllCompaniesFail: "getAllCompaniesFail",
  getSingleCompanyRequest: "getSingleCompanyRequest",
  getSingleCompanySuccess: "getSingleCompanySuccess",
  getSingleCompanyFail: "getSingleCompanyFail",
  getImageForCompanyRequest: "getImageForCompanyRequest",
  getImageForCompanySuccess: "getImageForCompanySuccess",
  getImageForCompanyFail: "getImageForCompanyFail",
  uploadImageRequest: "uploadImageRequest",
  uploadImageSuccess: "uploadImageSuccess",
  uploadImageFail: "uploadImageFail",
  editCompanyRequest: "editCompanyRequest",
  editCompanySuccess: "editCompanySuccess",
  editCompanyFail: "editCompanyFail",
  getCompanyVideoRequest: "getCompanyVideoRequest",
  getCompanyVideoSuccess: "getCompanyVideoSuccess",
  getCompanyVideoFail: "getCompanyVideoFail",
  companiesFilter: "companiesFilter",
  companyTags: "companyTags",
  editCompanyVideoRequest: "editCompanyVideoRequest",  
  editCompanyVideoSuccess: "editCompanyVideoSuccess",
  editCompanyVideoFail: "editCompanyVideoFail",
};