export const actions = {
	getAllUsersRequest: "getAllUsersRequest",
	getAllUsersSuccess: "getAllUsersSuccess",
	getAllUsersFail: "getAllUsersFail",
	blockUsersRequest: "blockUsersRequest",
	blockUsersSuccess: "blockUsersSuccess",
	blockUsersFail: "blockUsersFail",
	unblockUsersRequest: "unblockSelecetedUsersRequest",
	unblockUsersSuccess: "unblockSelecetedUsersSuccess",
	unblockUsersFail: "unblockSelecetedUsersFail",
	deleteUsersRequest: "deleteSelecetedUsersReuest",
	deleteUsersSuccess: "deleteSelecetedUsersSuccess",
	deleteUsersFail: "deleteSelecetedUsersFail",
	makeAdminRequest: "makeAdminSelecetedUsersRequest",
	makeAdminSuccess: "makeAdminSelecetedUsersSuccess",
	makeAdminFail: "makeAdminSelecetedUsersFail",
	makeUserRequest: "makeUserSelecetedUsersRequest",
	makeUserSuccess: "makeUserSelecetedUsersSuccess",
	makeUserFail: "makeUserSelecetedUsersFail",
};
